// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIk6hVRuKHsla7xZIyoO5GuDy1Gkl-qus',
    appId: '1:388685647537:web:7ba8688f173afbf0451c90',
    messagingSenderId: '388685647537',
    projectId: 'chatnight-73bc9',
    authDomain: 'chatnight-73bc9.firebaseapp.com',
    storageBucket: 'chatnight-73bc9.appspot.com',
    measurementId: 'G-244DNSCKCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAemBm0OsWLndTrVnuzMHbKUxgJWdSDanY',
    appId: '1:388685647537:android:dcd61bf276d683a5451c90',
    messagingSenderId: '388685647537',
    projectId: 'chatnight-73bc9',
    storageBucket: 'chatnight-73bc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_M5o0eHlyg-R26C60fZoXvSStMb-O0c',
    appId: '1:388685647537:ios:4451deec412309fd451c90',
    messagingSenderId: '388685647537',
    projectId: 'chatnight-73bc9',
    storageBucket: 'chatnight-73bc9.appspot.com',
    iosClientId: '388685647537-jkvm1588104adcdk672c0op2s7mfepev.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatnight',
  );
}
